# Generated by Django 4.0.4 on 2022-05-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
                ("rated", models.CharField(max_length=100)),
                ("released", models.CharField(max_length=100)),
                ("runtime", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("writer", models.CharField(max_length=1000)),
                ("actors", models.CharField(max_length=1000)),
                ("plot", models.CharField(max_length=1000)),
                ("language", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("awards", models.CharField(max_length=100)),
                ("poster", models.CharField(max_length=1000)),
                ("metascore", models.CharField(max_length=100)),
                ("imdb_rating", models.CharField(max_length=100)),
                ("imdb_votes", models.CharField(max_length=100)),
                ("imdb_id", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("dvd", models.CharField(max_length=100)),
                ("box_office", models.CharField(max_length=100)),
                ("production", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=100)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
    ]
